### PR TITLE
Export encounter, order

### PR DESCRIPTION
**Pull request by okeefm**

### CODE REVIEW

**Review by tstrass — CHANGES_REQUESTED** [review]
Don't we need an R3.1 template for this as well?

**Comment by okeefm** [comment]
I had one developed; not sure what happened to it. I'll see where it went.

**Comment by okeefm** [comment]
Added in the R3.1 template

**Review by tstrass — APPROVED** [review]
Looks good to me

**Review by mattrbianchi — APPROVED** [review]

**Pull request merged**
